spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.38.132:3306/easepay?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnectForPools=true&amp;autoReconnect=true
    username: ma_db_tourism
    password: 123456

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.mmnttech.ma.merchant.server.database.mappers
    
jedis :
  pool :
    host : 121.199.38.132
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000